<?php
/**
 * BlupApiTest
 * PHP version 8.1
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beekube BLUP Mellifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@beekube.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Beekube\BlupSDK\Test\Api;

use Beekube\BlupSDK\Configuration;
use Beekube\BlupSDK\ApiException;
use Beekube\BlupSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BlupApiTest Class Doc Comment
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BlupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for blupBlupPost
     *
     * Perform BLUP calculation.
     *
     */
    public function testBlupBlupPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for welcomeGet
     *
     * Welcome endpoint.
     *
     */
    public function testWelcomeGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
