<?php
/**
 * BlupsValueTest
 *
 * PHP version 8.1
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beekube BLUP Mellifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@beekube.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Beekube\BlupSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BlupsValueTest Class Doc Comment
 *
 * @description BlupsValue
 * @package     Beekube\BlupSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BlupsValueTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BlupsValue"
     */
    public function testBlupsValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
