<?php
/**
 * MatingSuggestionTest
 *
 * PHP version 8.1
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beekube BLUP Mellifera API
 *
 * SDK PHP pour l'API BLUP de Beekube - Calcul génétique des abeilles mellifères
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@beekube.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Beekube\BlupSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MatingSuggestionTest Class Doc Comment
 *
 * @description https://spec.openapis.org/oas/v3.1.0#contact-object
 * @package     Beekube\BlupSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MatingSuggestionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MatingSuggestion"
     */
    public function testMatingSuggestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blupScore"
     */
    public function testPropertyBlupScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "diversityScore"
     */
    public function testPropertyDiversityScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mateBlup"
     */
    public function testPropertyMateBlup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "queen"
     */
    public function testPropertyQueen()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "queenBlup"
     */
    public function testPropertyQueenBlup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalScore"
     */
    public function testPropertyTotalScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
