<?php
/**
 * QueenBeeInputTest
 *
 * PHP version 8.1
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beekube BLUP Mellifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@beekube.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Beekube\BlupSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * QueenBeeInputTest Class Doc Comment
 *
 * @description QueenBeeInput
 * @package     Beekube\BlupSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class QueenBeeInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "QueenBeeInput"
     */
    public function testQueenBeeInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "born"
     */
    public function testPropertyBorn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "queenbee"
     */
    public function testPropertyQueenbee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "apiaryDefault"
     */
    public function testPropertyApiaryDefault()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "droneParent"
     */
    public function testPropertyDroneParent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "evaluate"
     */
    public function testPropertyEvaluate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "queenbeeParent"
     */
    public function testPropertyQueenbeeParent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
