<?php
/**
 * BLUPInput
 *
 * PHP version 8.1
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beekube BLUP Mellifera API
 *
 * SDK PHP pour l'API BLUP de Beekube - Calcul génétique des abeilles mellifères
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@beekube.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beekube\BlupSDK\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Beekube\BlupSDK\ObjectSerializer;

/**
 * BLUPInput Class Doc Comment
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class BLUPInput extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'BLUPInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'data' => '\Beekube\BlupSDK\Models\QueenBeeInput[]',
        'evaluate' => 'int[]',
        'evaluateElimination' => 'int[]',
        'exploitation' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'data' => null,
        'evaluate' => null,
        'evaluateElimination' => null,
        'exploitation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'data' => false,
        'evaluate' => false,
        'evaluateElimination' => false,
        'exploitation' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'data' => 'data',
        'evaluate' => 'evaluate',
        'evaluateElimination' => 'evaluate_elimination',
        'exploitation' => 'exploitation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'data' => 'setData',
        'evaluate' => 'setEvaluate',
        'evaluateElimination' => 'setEvaluateElimination',
        'exploitation' => 'setExploitation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'data' => 'getData',
        'evaluate' => 'getEvaluate',
        'evaluateElimination' => 'getEvaluateElimination',
        'exploitation' => 'getExploitation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('evaluate', $data ?? [], null);
        $this->setIfExists('evaluateElimination', $data ?? [], null);
        $this->setIfExists('exploitation', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['data'] === null) {
            $invalidProperties[] = "'data' can't be null";
        }
        if ($this->container['evaluate'] === null) {
            $invalidProperties[] = "'evaluate' can't be null";
        }
        if ($this->container['evaluateElimination'] === null) {
            $invalidProperties[] = "'evaluateElimination' can't be null";
        }
        if ($this->container['exploitation'] === null) {
            $invalidProperties[] = "'exploitation' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Gets data
     *
     * @return \Beekube\BlupSDK\Models\QueenBeeInput[]
     */
    public function getData(): array
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param \Beekube\BlupSDK\Models\QueenBeeInput[] $data data
     *
     * @return $this
     */
    public function setData(array $data): static
    {
        if (is_null($data)) {
            throw new InvalidArgumentException('non-nullable data cannot be null');
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets evaluate
     *
     * @return int[]
     */
    public function getEvaluate(): array
    {
        return $this->container['evaluate'];
    }

    /**
     * Sets evaluate
     *
     * @param int[] $evaluate evaluate
     *
     * @return $this
     */
    public function setEvaluate(array $evaluate): static
    {
        if (is_null($evaluate)) {
            throw new InvalidArgumentException('non-nullable evaluate cannot be null');
        }
        $this->container['evaluate'] = $evaluate;

        return $this;
    }

    /**
     * Gets evaluateElimination
     *
     * @return int[]
     */
    public function getEvaluateElimination(): array
    {
        return $this->container['evaluateElimination'];
    }

    /**
     * Sets evaluateElimination
     *
     * @param int[] $evaluateElimination evaluateElimination
     *
     * @return $this
     */
    public function setEvaluateElimination(array $evaluateElimination): static
    {
        if (is_null($evaluateElimination)) {
            throw new InvalidArgumentException('non-nullable evaluateElimination cannot be null');
        }
        $this->container['evaluateElimination'] = $evaluateElimination;

        return $this;
    }

    /**
     * Gets exploitation
     *
     * @return int
     */
    public function getExploitation(): int
    {
        return $this->container['exploitation'];
    }

    /**
     * Sets exploitation
     *
     * @param int $exploitation exploitation
     *
     * @return $this
     */
    public function setExploitation(int $exploitation): static
    {
        if (is_null($exploitation)) {
            throw new InvalidArgumentException('non-nullable exploitation cannot be null');
        }
        $this->container['exploitation'] = $exploitation;

        return $this;
    }
}


