<?php
/**
 * QueenBeeInput
 *
 * PHP version 8.1
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Beekube BLUP Mellifera API
 *
 * SDK PHP pour l'API BLUP de Beekube - Calcul génétique des abeilles mellifères
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@beekube.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beekube\BlupSDK\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Beekube\BlupSDK\ObjectSerializer;

/**
 * QueenBeeInput Class Doc Comment
 *
 * @package  Beekube\BlupSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class QueenBeeInput extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'QueenBeeInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'born' => 'string',
        'queenbee' => 'int',
        'variety' => 'string',
        'apiaryDefault' => 'int',
        'died' => 'bool',
        'droneParent' => 'int',
        'evaluate' => 'array<string,\Beekube\BlupSDK\Models\Evaluation[]>',
        'queenbeeParent' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'born' => null,
        'queenbee' => null,
        'variety' => null,
        'apiaryDefault' => null,
        'died' => null,
        'droneParent' => null,
        'evaluate' => null,
        'queenbeeParent' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'born' => false,
        'queenbee' => false,
        'variety' => false,
        'apiaryDefault' => true,
        'died' => false,
        'droneParent' => true,
        'evaluate' => false,
        'queenbeeParent' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'born' => 'born',
        'queenbee' => 'queenbee',
        'variety' => 'variety',
        'apiaryDefault' => 'apiary_default',
        'died' => 'died',
        'droneParent' => 'drone_parent',
        'evaluate' => 'evaluate',
        'queenbeeParent' => 'queenbee_parent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'born' => 'setBorn',
        'queenbee' => 'setQueenbee',
        'variety' => 'setVariety',
        'apiaryDefault' => 'setApiaryDefault',
        'died' => 'setDied',
        'droneParent' => 'setDroneParent',
        'evaluate' => 'setEvaluate',
        'queenbeeParent' => 'setQueenbeeParent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'born' => 'getBorn',
        'queenbee' => 'getQueenbee',
        'variety' => 'getVariety',
        'apiaryDefault' => 'getApiaryDefault',
        'died' => 'getDied',
        'droneParent' => 'getDroneParent',
        'evaluate' => 'getEvaluate',
        'queenbeeParent' => 'getQueenbeeParent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('born', $data ?? [], null);
        $this->setIfExists('queenbee', $data ?? [], null);
        $this->setIfExists('variety', $data ?? [], null);
        $this->setIfExists('apiaryDefault', $data ?? [], null);
        $this->setIfExists('died', $data ?? [], false);
        $this->setIfExists('droneParent', $data ?? [], null);
        $this->setIfExists('evaluate', $data ?? [], null);
        $this->setIfExists('queenbeeParent', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['born'] === null) {
            $invalidProperties[] = "'born' can't be null";
        }
        if ($this->container['queenbee'] === null) {
            $invalidProperties[] = "'queenbee' can't be null";
        }
        if ($this->container['variety'] === null) {
            $invalidProperties[] = "'variety' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Gets born
     *
     * @return string
     */
    public function getBorn(): string
    {
        return $this->container['born'];
    }

    /**
     * Sets born
     *
     * @param string $born born
     *
     * @return $this
     */
    public function setBorn(string $born): static
    {
        if (is_null($born)) {
            throw new InvalidArgumentException('non-nullable born cannot be null');
        }
        $this->container['born'] = $born;

        return $this;
    }

    /**
     * Gets queenbee
     *
     * @return int
     */
    public function getQueenbee(): int
    {
        return $this->container['queenbee'];
    }

    /**
     * Sets queenbee
     *
     * @param int $queenbee queenbee
     *
     * @return $this
     */
    public function setQueenbee(int $queenbee): static
    {
        if (is_null($queenbee)) {
            throw new InvalidArgumentException('non-nullable queenbee cannot be null');
        }
        $this->container['queenbee'] = $queenbee;

        return $this;
    }

    /**
     * Gets variety
     *
     * @return string
     */
    public function getVariety(): string
    {
        return $this->container['variety'];
    }

    /**
     * Sets variety
     *
     * @param string $variety variety
     *
     * @return $this
     */
    public function setVariety(string $variety): static
    {
        if (is_null($variety)) {
            throw new InvalidArgumentException('non-nullable variety cannot be null');
        }
        $this->container['variety'] = $variety;

        return $this;
    }

    /**
     * Gets apiaryDefault
     *
     * @return int|null
     */
    public function getApiaryDefault(): ?int
    {
        return $this->container['apiaryDefault'];
    }

    /**
     * Sets apiaryDefault
     *
     * @param int|null $apiaryDefault apiaryDefault
     *
     * @return $this
     */
    public function setApiaryDefault(?int $apiaryDefault): static
    {
        if (is_null($apiaryDefault)) {
            array_push($this->openAPINullablesSetToNull, 'apiaryDefault');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apiaryDefault', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apiaryDefault'] = $apiaryDefault;

        return $this;
    }

    /**
     * Gets died
     *
     * @return bool|null
     */
    public function getDied(): ?bool
    {
        return $this->container['died'];
    }

    /**
     * Sets died
     *
     * @param bool|null $died died
     *
     * @return $this
     */
    public function setDied(?bool $died): static
    {
        if (is_null($died)) {
            throw new InvalidArgumentException('non-nullable died cannot be null');
        }
        $this->container['died'] = $died;

        return $this;
    }

    /**
     * Gets droneParent
     *
     * @return int|null
     */
    public function getDroneParent(): ?int
    {
        return $this->container['droneParent'];
    }

    /**
     * Sets droneParent
     *
     * @param int|null $droneParent droneParent
     *
     * @return $this
     */
    public function setDroneParent(?int $droneParent): static
    {
        if (is_null($droneParent)) {
            array_push($this->openAPINullablesSetToNull, 'droneParent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('droneParent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['droneParent'] = $droneParent;

        return $this;
    }

    /**
     * Gets evaluate
     *
     * @return array<string,\Beekube\BlupSDK\Models\Evaluation[]>|null
     */
    public function getEvaluate(): ?array
    {
        return $this->container['evaluate'];
    }

    /**
     * Sets evaluate
     *
     * @param array<string,\Beekube\BlupSDK\Models\Evaluation[]>|null $evaluate evaluate
     *
     * @return $this
     */
    public function setEvaluate(?array $evaluate): static
    {
        if (is_null($evaluate)) {
            throw new InvalidArgumentException('non-nullable evaluate cannot be null');
        }
        $this->container['evaluate'] = $evaluate;

        return $this;
    }

    /**
     * Gets queenbeeParent
     *
     * @return int|null
     */
    public function getQueenbeeParent(): ?int
    {
        return $this->container['queenbeeParent'];
    }

    /**
     * Sets queenbeeParent
     *
     * @param int|null $queenbeeParent queenbeeParent
     *
     * @return $this
     */
    public function setQueenbeeParent(?int $queenbeeParent): static
    {
        if (is_null($queenbeeParent)) {
            array_push($this->openAPINullablesSetToNull, 'queenbeeParent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('queenbeeParent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['queenbeeParent'] = $queenbeeParent;

        return $this;
    }
}


